/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        canvas: "#0A0A0A",
        surface: "#141414",
        "surface-dark": "#0A0A0A",
        "surface-container": "#201F1F",
        "surface-container-low": "#1C1B1B",
        "surface-container-lowest": "#0E0E0E",
        "surface-container-high": "#2A2A2A",
        "surface-container-highest": "#353534",
        "surface-bright": "#3A3939",
        "surface-dim": "#131313",
        "primary": "#FF5722",
        "primary-orange": "#FF5722",
        "primary-hover": "#E64A19",
        "primary-container": "#FF5722",
        "on-primary-container": "#FFFFFF",
        "on-primary": "#5F1500",
        "secondary": "#C7C6C6",
        "secondary-muted": "#B4B4B4",
        "secondary-dim": "#8A8A8A",
        "tertiary": "#76FF03",
        "acid-green": "#76FF03",
        "neon-yellow": "#FFEB3B",
        "alert-red": "#E53935",
        "electric-blue": "#2196F3",
        "error": "#E53935",
        "warning": "#FFEB3B",
        "info": "#2196F3",
        "on-surface": "#E5E2E1",
        "on-surface-variant": "#E4BEB4",
      },
      fontFamily: {
        anton: ["Anton", "sans-serif"],
        display: ["Anton", "sans-serif"],
        headline: ["Anton", "sans-serif"],
        bebas: ["'Bebas Neue'", "sans-serif"],
        badge: ["'Bebas Neue'", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        code: ["'JetBrains Mono'", "monospace"],
      },
      animation: {
        marquee: "marquee 25s linear infinite",
        "marquee-fast": "marquee 18s linear infinite",
        "marquee-slow": "marquee 35s linear infinite",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin-mobile": "1rem",
        "margin-desktop": "3rem",
        "gutter-desktop": "1.5rem",
      },
    },
  },
  plugins: [],
};
